"""Add cart and cart_items tables

Revision ID: 44756e23af6c
Revises: 6948748cabf7
Create Date: 2026-07-31 01:48:37.935062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44756e23af6c'
down_revision: Union[str, None] = '6948748cabf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_expansions_category_id'), 'expansions', ['category_id'], unique=False)
    op.create_index('idx_products_slug', 'products', ['slug'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('idx_users_email', table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index('idx_products_slug', table_name='products')
    op.drop_index(op.f('ix_expansions_category_id'), table_name='expansions')
    # ### end Alembic commands ###
